version: "3.7"

name: bar

services:
  gateway:
    container_name: bar.gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5010:80
    volumes:
      - ~/.vsdbg:/remote_debugger/
    labels:
      - SERVICE_CHECK_HTTP=/health
      - SERVICE_CHECK_INTERVAL=20s
      - SERVICE_NAME=gateway

  brand:
    build:
      context: ./brand.service
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5011:80
    labels:
      - SERVICE_CHECK_HTTP=/health
      - SERVICE_CHECK_INTERVAL=20s
      - SERVICE_NAME=brand.service
    volumes:
      - ~/.vsdbg:/remote_debugger/

  consul:
    container_name: bar.consul
    image: consul:1.15.4
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
    networks:
      - bar_network

  consul-registrator:
    container_name: bar.consul.registrator
    image: gliderlabs/registrator:master
    command: "-explicit=true -internal=true consul://consul:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bar_network
    depends_on:
      - consul

  postgres:
    container_name: bar.postgres
    image: polaris/postgres:local
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_db:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    hostname: jaeger
    networks:
      - bar_network
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411



  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - bar_network

  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "baeldung:1:1"
  #   networks:
  #     - bar_network

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   networks:
  #     - bar_network
      
volumes:
  postgres_db:

networks:
  bar_network:

