version: "3.7"

name: bar

services:
  gateway:
    container_name: bar.gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5010:80
    volumes:
      - ~/.vsdbg:/remote_debugger/
    labels:
      - SERVICE_CHECK_HTTP=/health
      - SERVICE_CHECK_INTERVAL=20s
      - SERVICE_NAME=gateway

  brand:
    build:
      context: ./brand.service
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5011:80
    labels:
      - SERVICE_CHECK_HTTP=/health
      - SERVICE_CHECK_INTERVAL=20s
      - SERVICE_NAME=brand.service
    volumes:
      - ~/.vsdbg:/remote_debugger/

  consul:
    container_name: bar.consul
    image: consul:1.15.4
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
    networks:
      - bar_network

  consul-registrator:
    container_name: bar.consul.registrator
    image: gliderlabs/registrator:master
    command: "-explicit=true -internal=true consul://consul:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bar_network
    depends_on:
      - consul

  postgres:
    container_name: bar.postgres
    image: polaris/postgres:local
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
      - bar_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:

networks:
  bar_network:

